name: Deploy to Dev
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - name: Checkout files and setup environment
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.1
      - name: Copy images to deployment directory
        run: |
          echo "contents inside wp-content git before"
          ls -l ./wp-content/uploads/2024/03/
          if sudo rsync -av --rsh="/usr/bin/sshpass -p "Inf0d@t1996" ssh -o StrictHostKeyChecking=no -l root" ./wp-content/uploads/2024/03/  infodatdev-test@infodatdev.sftp.wpengine.com:2222/wp-content/uploads/2024/03/; then
            echo "Images copied successfully."
          else
            echo "Failed to copy images."
            exit 1
          fi
          echo "contents inside wp-content git after"
      # cp -r ./wp-content/uploads/   /home/runner/work/demo_project_website/demo_project_website/wp-content/uploads/
      - name: GitHub Action Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3
        with: 
          WPE_SSHG_KEY_PRIVATE: ${{secrets.WP_SSHG_KEY_PRIVATE}}
          WPE_ENV: infodatdev
          # Deploy Options
          #REMOTE_PATH: "wp-content/"
          PHP_LINT: TRUE
          CACHE_CLEAR: TRUE


