name: Deploy to Dev
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - name: Checkout files and setup environment
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.1
      - name: Checkout
        uses: actions/checkout@v3
      - name: Copy images to deployment directory
        run: |
          #ls -l
          cp ./wpcontent/uploads/   /wpcontent/uploads/
      - name: GitHub Action Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          # ARGS: "nvm install v20.11.1"
          # Deploy vars
          WPE_SSHG_KEY_PRIVATE: ${{secrets.WP_SSHG_KEY_PRIVATE}}
          WPE_ENV: infodatdev
          # Deploy Options
          #REMOTE_PATH: "wp-content/"
          PHP_LINT: TRUE
          CACHE_CLEAR: TRUE


